### ISSUE TITLE
libboost-filesystem1.71 not compatable with binaries

### ISSUE THREAD

**Issue by text70** [VecoOfficial/Veco#8]
Trying to run the latest binaries on Ubuntu 20.04 I receive the following:

`./vecod: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
`

Output from 'dpkg -s libboost-filesystem-dev | grep 'Version' 
`Version: 1.71.0.0ubuntu2
`

**Comment by masicode** [comment]
sudo apt-get install libboost-all-dev

**Comment by text70** [comment]
> sudo apt-get install libboost-all-dev

`$ dpkg -s libboost-all-dev | grep 'Version'
Version: 1.71.0.0ubuntu2
`
still unable to run ./vecod

**Comment by masicode** [comment]
wget http://archive.ubuntu.com/ubuntu/pool/main/b/boost1.58/libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb
sudo dpkg -i libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb

**Comment by masicode** [comment]
`wget http://archive.ubuntu.com/ubuntu/pool/main/b/boost1.58/libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb`

`sudo dpkg -i libboost-filesystem1.58.0_1.58.0+dfsg-5ubuntu3.1_amd64.deb`
